bin2NpmVersion = "0"
outDir         = "npm"

[targetPackageJson]
    name        = "bin2npm"
    version     = "0.0.6"
    description = "A cli tool by @bjesuiter which takes one or more binaries for different platforms and wraps them into an npm package for distribution. Can also be used via bin2npm package on npmjs.org"

[[binaries]]
    path = "compiled/bin2npm_linux_x64"
    # platform should be one of nodejs's os.platform() values:
    # for Node 16 LTS: 'aix', 'darwin', 'freebsd','linux', 'openbsd', 'sunos', and 'win32'
    # see https://nodejs.org/docs/latest-v16.x/api/os.html#osplatform
    # These are only the allowed values. You have to provide the correct binary for this to work.
    platform = "linux"
    # arch should be one of nodejs's os.arch() values: 
    # for Node 16 LTS: 'arm', 'arm64', 'ia32', 'mips', 'mipsel', 'ppc', 'ppc64', 's390', 's390x', and 'x64'
    # see https://nodejs.org/docs/latest-v16.x/api/os.html#osarch
    # These are only the allowed values. You have to provide the correct binary for this to work.
    arch = "x64"

[[binaries]]
    path     = "compiled/bin2npm_macos_x64"
    platform = "darwin"
    arch     = "x64"

[[binaries]]
    path     = "compiled/bin2npm_macos_arm"
    platform = "darwin"
    arch     = "arm64"

[[binaries]]
    path     = "compiled/bin2npm_windows_x64.exe"
    platform = "win32"
    arch     = "x64"

[[extraAssets]]
    from = "Readme.md"
    to   = "Readme.md"
