name: Deploy npm
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
env:
  DENO_DIR: .deno-cache
jobs:
  Compile-Bin2Npm:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Deno
        # You may pin to the exact commit or the version.
        # uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31
        uses: denoland/setup-deno@v1.1.2
        # with:
        #     # The Deno version to install. Can be a semver version of a stable release, "canary" for the latest canary, or the Git hash of a specific canary release.
        #     deno-version: # optional, default is 1.x
      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: deno task pack-assets
      - run: deno task compile
      - run: deno task assemble-npm
    #   - run: deno task publish-npm
